FROM golang:bookworm

# Install capture libraries
RUN apt-get update && \
  apt-get -y install libpcap0.8 libpcap0.8-dev && \
  apt-get -y -q install wget lsb-release gnupg && \
  apt-get -y install tcpreplay && \
  apt-get -y install tcpdump

# Set the working directory to ...
WORKDIR /go/src/github.com/traffic-refinery/traffic-refinery/

# Add folder to drop output.
RUN mkdir /out
